export const SET_IS_INFO_ALERT = 'SET_IS_INFO_ALERT';
export const SET_IS_QUESTION_ALERT = 'SET_IS_QUESTION_ALERT';

export const UPDATE_VINYLS_ON_AFTER_SEARCH_PAGE = 'UPDATE_VINYLS_ON_AFTER_SEARCH_PAGE';

export const INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS';

export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_IS_WAIT_RESPONSE = 'SET_IS_WAIT_RESPONSE';
// export const SET_IS_MAIL_CONFIRM = 'SET_IS_MAIL_CONFIRM';
export const SET_EDIT_PROFILE_DATA = 'SET_EDIT_PROFILE_DATA';
// export const SET_IS_PROFILE_EDITED = 'SET_IS_PROFILE_EDITED';
// export const SET_IS_PROFILE_DELETED = 'SET_IS_PROFILE_DELETED';

export const UPDATE_VINYLS_LIST_ON_CATALOG_PAGE = 'UPDATE_VINYLS_LIST_ON_CATALOG_PAGE';

export const SET_IS_PASSWORD_CHANGED = 'SET_IS_PASSWORD_CHANGED'

// export const SET_IS_CONTACT_US_SUCCESS = 'SET_IS_CONTACT_US_SUCCESS';

export const SET_DELETE_PROFILE_QUESTION = "SET_DELETE_PROFILE_QUESTION";

export const SET_IS_WAIT_RECOVERY_RESPONSE = 'SET_IS_WAIT_RECOVERY_RESPONSE';
// export const SET_IS_NEW_PASSWORD_UPDATED = 'SET_IS_NEW_PASSWORD_UPDATED';
export const SET_RECOVERY_DATA = 'SET_RECOVERY_DATA';
export const RESET_RECOVERY_DATA = 'RESET_RECOVERY_DATA';

export const UPDATE_ONE_VINYL_PAGE = 'UPDATE_ONE_VINYL_PAGE';

// export const SET_IS_RECOVERY_MAIL_SENT = 'SET_IS_RECOVERY_MAIL_SENT';

// export const SET_REGISTRATION_INFO = 'SET_REGISTRATION_INFO';

export const UPDATE_SEARCH_FIELD = 'UPDATE_SEARCH_FIELD';

export const UPDATE_STORES_ON_STORES_PAGE = 'UPDATE_STORES_ON_STORES_PAGE';